from utils.models import Show

BRAVO_SLATE = [
    Show(1,  "Real Housewives (ATL)",    "Reality",     20, 750,  2.80, 95, 1,  "Bravo",
         description="Wealthy Atlanta women navigate friendships, business ventures, and reunion-stage feuds."),
    Show(2,  "Real Housewives (NYC)",    "Reality",     16, 720,  2.30, 88, 3,  "Bravo",
         description="Manhattan socialites clash over old grudges, new money, and who wasn't invited to dinner."),
    Show(3,  "Below Deck",              "Reality",     16, 700,  1.90, 82, 4,  "Bravo",
         description="A yacht crew serves demanding charter guests while their own on-board romances implode."),
    Show(4,  "Top Chef",               "Competition",  14, 800,  2.10, 90, 1,  "Bravo",
         description="Rising chefs face elimination challenges judged by a rotating panel of culinary heavyweights."),
    Show(5,  "Vanderpump Rules",        "Reality",     20, 650,  1.60, 75, 1,  "Bravo",
         description="Restaurant staff at a West Hollywood hotspot turn workplace drama into a season-long soap opera."),
    Show(6,  "Project Runway",          "Competition",  16, 900,  1.40, 70, 7,  "Bravo",
         description="Fashion designers race the clock to construct runway-ready looks under a brutal weekly twist."),
    Show(7,  "Shahs of Sunset",         "Reality",     12, 600,  0.90, 55, 3,  "Bravo",
         description="A tight-knit Persian-American friend group in LA mixes lavish parties with real family tension."),
    Show(8,  "Million Dollar Listing",  "Reality",     10, 550,  1.10, 60, 4,  "Bravo",
         description="Rival luxury real estate agents chase seven-figure commissions and each other's clients."),
    Show(9,  "Inside the Actors Studio","Talk",        12, 400,  0.70, 65, 2,  "Bravo",
         description="A single-set interview show puts working actors and directors through a deep-dive Q&A format."),
    Show(10, "Watch What Happens Live", "Talk",        30, 250,  0.80, 72, 1,  "Bravo",
         description="A late-night clubhouse special where Bravo stars field callers' questions live and unfiltered."),
    Show(11, "The New Normal",          "Scripted",    22, 1200, 0.60, 40, 9,  "Bravo",
         description="A single-camera sitcom follows a gay couple and their surrogate navigating a modern family."),
    Show(12, "Gallery Girls",           "Reality",      8, 500,  0.50, 30, 8,  "Bravo",
         description="Aspiring art-world assistants intern at competing NYC galleries for little pay and less patience."),
    Show(13, "NYC Prep",               "Reality",      8, 480,  0.40, 28, 6,  "Bravo",
         description="Manhattan prep-school teens juggle exclusive parties, family pressure, and college anxiety."),
    Show(14, "Southern Charm",         "Reality",     10, 580,  1.20, 62, 3,  "Bravo",
         description="Charleston's old-money social scene collides with new scandal every reunion season."),
    Show(15, "Flipping Out",           "Reality",     12, 520,  0.90, 55, 2,  "Bravo",
         description="A perfectionist house-flipper's renovation crew absorbs the brunt of his exacting standards."),
    Show(16, "Work of Art",            "Competition",  10, 700,  0.60, 42, 6,  "Bravo",
         description="Visual artists compete on themed installations judged by gallerists and critics each week."),
    Show(17, "Tabatha Takes Over",     "Reality",     10, 450,  0.80, 50, 5,  "Bravo",
         description="A no-nonsense consultant overhauls failing small businesses in a single high-pressure week."),
    Show(18, "Most Eligible Dallas",   "Reality",      8, 480,  0.50, 32, 7,  "Bravo",
         description="Dallas's wealthiest young singles compete for status as much as for each other."),
    Show(19, "Newlyweds: First Year",  "Reality",      8, 500,  0.70, 45, 4,  "Bravo",
         description="Three couples document the unglamorous adjustments of their first twelve months of marriage."),
    Show(20, "Unscripted Pilot",       "Reality",      6, 420,  0.90, 58, 10, "Bravo",
         description="An untested reality format gets a short trial order to see if the concept has legs."),
]

# 20 shows, $250-320K/ep, 36-month amortization (cheaper, simpler — Level 1)
OXYGEN_SLATE = [
    Show(21, "Snapped",                    "True Crime",  20, 300, 0.80, 70, 1,  "Oxygen",
         description="A long-running anthology reconstructing real cases of women who committed murder."),
    Show(22, "Cold Justice",               "True Crime",  14, 280, 0.90, 68, 3,  "Oxygen",
         description="Former prosecutors and detectives reopen unsolved homicide cases for small-town police departments."),
    Show(23, "The Disappearance",          "True Crime",   8, 260, 0.60, 52, 5,  "Oxygen",
         description="Each episode traces the investigation behind one person who vanished without a trace."),
    Show(24, "Preachers of LA",            "Reality",     10, 250, 0.50, 44, 7,  "Oxygen",
         description="Prominent LA pastors balance ministry, ego, and congregation politics in front of the cameras."),
    Show(25, "Oxygen True Crime Block",    "True Crime",  16, 270, 0.70, 60, 2,  "Oxygen",
         description="A rotating anthology strand bundling standalone true-crime cases into one weekly programming block."),
    Show(26, "Killer Motive",              "True Crime",  12, 290, 0.65, 58, 4,  "Oxygen",
         description="Investigators dig past the obvious suspect to uncover the real motive behind each murder."),
    Show(27, "Wanted: Dead or Alive",      "True Crime",  10, 260, 0.55, 50, 6,  "Oxygen",
         description="U.S. Marshals track fugitives across state lines in real manhunt case files."),
    Show(28, "Behind Bars",                "True Crime",   8, 240, 0.45, 42, 8,  "Oxygen",
         description="Inmates and corrections officers describe daily life inside a maximum-security facility."),
    Show(29, "Girls Incarcerated",         "Reality",     10, 255, 0.60, 55, 9,  "Oxygen",
         description="Teenage girls at a juvenile detention facility work toward rehabilitation and release."),
    Show(30, "License to Kill",            "True Crime",  12, 280, 0.70, 62, 1,  "Oxygen",
         description="Profiles of killers who used their profession or position of trust to commit murder."),
    Show(31, "The Accused",                "True Crime",   8, 270, 0.55, 48, 3,  "Oxygen",
         description="Courtroom-driven cases follow a defendant's trial from indictment to verdict."),
    Show(32, "Forensic Files II",          "True Crime",  20, 230, 0.75, 65, 2,  "Oxygen",
         description="Physical evidence and forensic science crack cold cases that stumped investigators for years."),
    Show(33, "Buried in the Backyard",     "True Crime",  10, 260, 0.50, 46, 10, "Oxygen",
         description="Missing-persons cases that end with a shocking discovery close to home."),
    Show(34, "Over My Dead Body",          "True Crime",   6, 320, 0.65, 58, 5,  "Oxygen",
         description="Inheritance, insurance, and greed turn deadly in this anthology of murder-for-money cases."),
    Show(35, "Final Appeal",               "True Crime",   8, 250, 0.45, 40, 7,  "Oxygen",
         description="Legal teams revisit contested convictions as a case heads toward its last chance at appeal."),
    Show(36, "Injustice with Nancy Grace", "True Crime",  12, 275, 0.60, 55, 4,  "Oxygen",
         description="A veteran legal commentator breaks down high-profile cases and where the system went wrong."),
    Show(37, "Killer Couples",             "True Crime",  16, 240, 0.65, 58, 1,  "Oxygen",
         description="Romantic partnerships turn homicidal in this anthology of couples who killed together."),
    Show(38, "A Killing on the Cape",      "True Crime",   6, 300, 0.50, 45, 6,  "Oxygen",
         description="A single-case limited series unravels a murder that shook a small coastal town."),
    Show(39, "Dateline-Style Pilot",       "True Crime",   8, 260, 0.70, 60, 3,  "Oxygen",
         description="A newsmagazine-format pilot pairing long-form investigative narration with archival interviews."),
    Show(40, "Crime Scene Kitchen",        "Competition", 12, 290, 0.55, 48, 8,  "Oxygen",
         description="Home cooks reconstruct a dessert from crime-scene-style evidence photos alone, without a recipe."),
]

# 10 shows, $1.5M-$3M/ep, 36-month amortization (SVOD originals — Level 3)
PEACOCK_SLATE = [
    Show(41, "Dr. Death",               "Drama",    8,  2500, 1.20, 85, 1, "Peacock",
         description="A charismatic surgeon's rising body count exposes the hospital system that enabled him."),
    Show(42, "Angelyne",                "Drama",    6,  2000, 0.90, 78, 3, "Peacock",
         description="A self-invented LA billboard icon's mysterious past unravels across four different narrators."),
    Show(43, "Rutherford Falls",        "Comedy",  10,  1800, 0.75, 70, 2, "Peacock",
         description="A small town's statue controversy pits lifelong friends against their own history and identity."),
    Show(44, "Brave New World",         "Drama",    9,  3000, 0.85, 80, 1, "Peacock",
         description="A genetically engineered utopia begins to crack once an outsider exposes what it costs to belong."),
    Show(45, "The Thing About Pam",     "Drama",    6,  2200, 1.10, 82, 4, "Peacock",
         description="A true-crime-adjacent limited series follows a small-town murder investigation's stranger-than-fiction twist."),
    Show(46, "Kenan",                   "Comedy",  12,  1500, 0.70, 65, 2, "Peacock",
         description="A widowed morning-show host tries to co-parent, co-host, and keep his family together at once."),
    Show(47, "Girls5eva",               "Comedy",  10,  1800, 0.80, 72, 3, "Peacock",
         description="A one-hit-wonder girl group attempts an unlikely reunion two decades after their single flopped."),
    Show(48, "MacGruber",               "Comedy",   8,  2000, 0.75, 68, 1, "Peacock",
         description="A disgraced special-ops disaster is pulled out of hiding for one last impossible mission."),
    Show(49, "The Resort",              "Drama",    8,  2800, 0.95, 80, 6, "Peacock",
         description="A couple's rocky vacation collides with a fifteen-year-old missing-persons mystery at their resort."),
    Show(50, "Poker Face",              "Drama",   10,  2400, 1.05, 83, 5, "Peacock",
         description="A human lie detector goes on the run, solving a new murder-of-the-week in every town she lands in."),
]
